#!/bin/bash

IMAGE_NAME="nutn-my-python"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

if [[ "$(docker images -q $IMAGE_NAME 2> /dev/null)" == "" ]]; then
	echo "Docker image $IMAGE_NAME not found. Building..."
	docker build -f $SCRIPT_DIR/../Docker/Python/Dockerfile -t $IMAGE_NAME .
fi

execute_file=$1
if [ ! -f "$execute_file" ]; then
    echo "Error: $execute_file does not exist or is not a regular file."
	exit 1
fi

docker run -it --rm -v "$(pwd):/app" $IMAGE_NAME python /app/$execute_file